name: Hat On Dog
description-short: A Podcasting Network
description: <em>Hat On Dog Productions</em> is a podcasting network, featuring comedy, music, and culture.
email: dog@hatondog.com

#social
facebook: hatondog
twitter: hatondog
soundcloud: radio4scotland

url: http://hatondog.com
#url: http://localhost:4000


defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      image: logo.png
  -
    scope:
      path: ""
      type: podcasts
    values:
      layout: "podcast"

collections:
  podcasts:
    output: true
    permalink: /podcasts/:path/