name: Hat On Dog
description-short: A Podcasting Network
description: <em>Hat On Dog Productions</em> is a podcasting network, featuring comedy, music, and culture.
email: dog@hatondog.com

#social
facebook: hatondog
twitter: hatondog
soundcloud: radio4scotland

url: http://hatondog.com
#url: http://localhost:4000

gems:
  - jekyll-sitemap
  
collections:
  podcasts:
    output: true
    permalink: /:collection/:path/
  episodes:
    output: true
    permalink: /podcasts/:path/:title/
  rss:
    output: true
    permalink: /podcasts/:path/feed.xml

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      image: logo.png
  -
    scope:
      path: ""
      type: podcasts
    values:
      layout: "podcast"
  -
    scope:
      path: ""
      type: episodes
    values:
      layout: "episode"
  -
    scope:
      path: ""
      type: rss
    values:
      layout: "rss"
  -
    scope:
      path: "podcasts/hmm-interesting-choice"
    values:
      podcast: hmm-interesting-choice
      image: logo-hmmchoice.jpg
  -
    scope:
      path: "podcasts/podghast-spooktacular"
    values:
      podcast: podghast-spooktacular
      image: logo-podghast.png
  -
    scope:
      path: "podcasts/dessert-island-discs"
    values:
      podcast: dessert-island-discs
      image: logo-dessert.jpg
  -
    scope:
      path: "podcasts/verse-chorus-verse"
    values:
      podcast: verse-chorus-verse
      image: logo-vcv.jpg