name: Hat On Dog
description-short: A Podcasting Network
description: <em>Hat On Dog Productions</em> is a podcasting network, featuring comedy, music, and culture.
email: dog@hatondog.com

#social
facebook: hatondog
twitter: hatondog
soundcloud: hatondog

url: http://hatondog.com
#url: http://localhost:4000

gems:
  - jekyll-sitemap
  
collections:
  podcasts:
    output: true
    permalink: /:collection/:path/
  episodes:
    output: true
    permalink: /podcasts/:path/:title/
  rss:
    output: true
    permalink: /podcasts/:path/feed.xml

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      image: logo.png
  -
    scope:
      path: ""
      type: podcasts
    values:
      layout: "podcast"
  -
    scope:
      path: ""
      type: episodes
    values:
      layout: "episode"
  -
    scope:
      path: ""
      type: rss
    values:
      layout: "rss"
  -
    scope:
      path: "_episodes/hmm-interesting-choice"
    values:
      podcast: "hmm-interesting-choice"
      image: "logo-hmmchoice.jpg"
  -
    scope:
      path: "_episodes/podghast-spooktacular"
    values:
      podcast: "podghast-spooktacular"
      image: "logo-podghast.png"
  -
    scope:
      path: "_episodes/dessert-island-discs"
    values:
      podcast: "dessert-island-discs"
      image: "logo-dessert.jpg"
  -
    scope:
      path: "_episodes/verse-chorus-verse"
    values:
      podcast: "verse-chorus-verse"
      image: "logo-vcv.jpg"
  -
    scope:
      path: "_episodes/kuwkuwtk"
    values:
      podcast: "kuwkuwtk"
      image: "logo-kuwkuwtk.jpg"
  -
    scope:
      path: "_episodes/dash-kapital"
    values:
      podcast: "dash-kapital"
      image: "logo-dashkapital.png"
  -
    scope:
      path: "_episodes/can-i-just-say-apprentice"
    values:
      podcast: "can-i-just-say-apprentice"
      image: "logo-can-you-just-say.png"
  -
    scope:
      path: "_episodes/whose-wine-is-it-anyway"
    values:
      podcast: "whose-wine-is-it-anyway"
      image: "logo-whose-wine-is-it-anyway.png"
  -
    scope:
      path: "_episodes/the-garfiles"
    values:
      podcast: "the-garfiles"
      image: "logo-garfiles.png"

